# FactionsUUID by drtshock
# Report issues https://github.com/drtshock/Factions/issues?state=open
# Live support http://webchat.esper.net/?channels=drtshock&prompt=1

# Made with love <3

# Debug
# Turn this on if you are having issues with something and working on resolving them.
# This will spam your console with information that is useful if you know how to read the source.
# It's suggested that you only turn this on at the direction of a developer.
debug: false


# Configuration section for Scoreboards
# This will allow you to completely customize how your scoreboards look.
# Make sure that no lines are duplicates of each other otherwise only the first will display.
# Use &0-9a-f for colors and include messages in "quotes"
scoreboard:

# How long do we want scoreboards to stay if set temporarily.
  expiration: 7

# FInfo scoreboard is displayed when a player walks into a new Faction's territory.
# Scoreboard disappears after <expiration> seconds.
# Things to be replaced in this:
# {power} - faction's power. {chunks} - total claimed chunks. {members} - total members.
# {online} - online members. {leader} - faction's leader. {open} - shows either true or false if open.
# The title of the scoreboard will be the Faction's tag and colored according to the relation with the player's Faction.
# Commenting this section out will cause the info to appear in chat as the plugin originally did.
  finfo:
    - "&6Power"
    - "{power}"
    - "&3Members"
    - "{online}/{members}"
    - "&4Leader"
    - "{leader}"
    - "&bTerritory"
    - "{chunks}"